openapi: 3.0.0
info:
  version: 1.9.5
  title: Fakedex
  description: Le fakedex de fakemon créer pour un projet de rpg style pokemon et le cadre du projet finale en cours de Services Web au Cégep de Victoriaville.
  
servers: 
  - url: http://fakedex.loc
paths:
  /:
    get:
      tags:
        - Général
      summary: Message de bienvenue
      description: ''
      responses:
        '200': 
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                    message : 'Générateur de fakemon'
  
  /apikey:
    get:
      tags: 
        - Api Key
      summary: Recherche d'une clé api ou créer/renouvelle une clé api pour un compte.
      description: La clé d'api fourni est un UUID en string pour s'assurer que chacune est unique.
      security:
        - AccountAuth: []
      parameters:
        - in: query    
          name:  nouvelle
          schema:
            type: integer
            default: 0
          description: "Le paramètre est optionnel. Cependant, il prend en compte seulement la valeur 0 et 1. (0 = faux et 1 = vrai)"   
      responses:
        '200': 
          description: Lorsque les informationes sont valides dans le header.
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                example:
                  api_key: "e65d7004-a893-41ad-9436-4ecadf9ddc7e"
        '401': 
          description: Lorsque les informations sont invalides dans le header.
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                example:
                  erreur: "Requête invalide"


  /fakemon/{id}:
      put:
        tags: 
          - Fakemon
        summary: Permet de modifier un fakemon.
        description: Il y a besoin d'une clé api dans le header pour pouvoir modifier un fakemon.
        security:
        - ApiKeyAuth: [] 
        requestBody:
          description: Les information du fakemon a modifié.
          required: true
          content:
            application/json:
               schema:
                type: object
                properties:
                  nom:
                    type: string
                  id_type1:
                    type: integer
                  id_type2:
                    type: integer
                  hp:
                    type: integer
                  atk:
                    type: integer
                  def:
                    type: integer
                  sp_atk:
                    type: integer
                  sp_def:
                    type: integer
                  speed: 
                    type: integer
                  description:
                    type: string
                example:
                  nom: "Octonite"
                  id_type1: 12
                  id_type2: 1
                  hp: 120
                  atk: 50
                  def: 300
                  sp_atk: 250
                  sp_def: 75
                  speed: 60
                  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."
                  
        responses:
          '200': 
            description: Lorsque le fakemon a été modifié.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nom:
                      type: string
                    id_type1:
                      type: integer
                    id_type2:
                      type: integer
                    hp:
                      type: integer
                    atk:
                      type: integer
                    def:
                      type: integer
                    sp_atk:
                      type: integer
                    sp_def:
                      type: integer
                    speed: 
                      type: integer
                    description:
                      type: string
                    id_usager:
                      type: integer
                example:
                  id: 253
                  nom: "Octonite"
                  id_type1: 12
                  id_type2: 1
                  hp: 120
                  atk: 50
                  def: 300
                  sp_atk: 250
                  sp_def: 75
                  speed: 60
                  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."
                  id_usager: 500
          '201': 
            description: Lorsque le fakemon n'existait pas et en crée un nouveau à la place.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nom:
                      type: string
                    id_type1:
                      type: integer
                    id_type2:
                      type: integer
                    hp:
                      type: integer
                    atk:
                      type: integer
                    def:
                      type: integer
                    sp_atk:
                      type: integer
                    sp_def:
                      type: integer
                    speed: 
                      type: integer
                    description:
                      type: string
                    id_usager:
                      type: integer
                example:
                  id: 500
                  nom: "Octonite"
                  id_type1: 12
                  id_type2: 1
                  hp: 120
                  atk: 50
                  def: 300
                  sp_atk: 250
                  sp_def: 75
                  speed: 60
                  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."
                  id_usager: 500
          '401': 
            description: Lorsque les informations sont invalides dans le header.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                  example:
                    erreur: "Requête invalide"
      delete:
        tags: 
          - Fakemon
        summary: Permet de supprimer un fakemon selon son id.
        description: Il y a besoin d'une clé api dans le header pour pouvoir supprimer un fakemon.
        security:
        - ApiKeyAuth: [] 
        responses:
          '200': 
            description: Lorsque le fakemon a été supprimer avec succès.
            content:
              application/json:
                 schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nom:
                      type: string
                    id_type1:
                      type: integer
                    id_type2:
                      type: integer
                    hp:
                      type: integer
                    atk:
                      type: integer
                    def:
                      type: integer
                    sp_atk:
                      type: integer
                    sp_def:
                      type: integer
                    speed: 
                      type: integer
                    description:
                      type: string
                    id_usager:
                      type: integer
                  example:
                    id: 500
                    nom: "Octonite"
                    id_type1: 12
                    id_type2: 1
                    hp: 120
                    atk: 50
                    def: 300
                    sp_atk: 250
                    sp_def: 75
                    speed: 60
                    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."
                    id_usager: 222
          '401': 
            description: Lorsque les informations sont invalides dans le header.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                  example:
                    erreur: "Requête invalide"
          '404': 
            description: Lorsque le id fourni est inexistant.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                  example:
                    erreur: "Id inexistant"

  /fakemon:
    get:
      tags:
        - Fakemon
      summary: Récuppérer la liste des fakemon qui ont été générer par l'usager.
      description: Il y a besoin d'une clé api dans le header pour pouvoir avoir accès à la liste.
      security:
      - ApiKeyAuth: [] 
      responses:
        '200': 
          description: Renvoi la liste des fakemons.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nom:
                          type: string
                        id_type1:
                          type: integer
                        id_type2:
                          type: integer
                        hp:
                          type: integer
                        atk:
                          type: integer
                        def:
                          type: integer
                        sp_atk:
                          type: integer
                        sp_def:
                          type: integer
                        speed: 
                          type: integer
                        description:
                          type: string
                        id_usager:
                          type: integer
                example:
                    data : [
                      {
                        id: 1,
                        nom: "Léviathan",
                        id_type1: 4,
                        id_type2: 17,
                        hp: 500,
                        atk: 240,
                        def: 150,
                        sp_atk: 100,
                        sp_def: 100,
                        speed: 25,
                        description: "Monstre mythologique des océans qui a détruit l'Atlantide selon la légende.",
                        id_usager: 24
                      },
                      {
                        ...: ...
                      }
                    ]
        '401': 
          description: Lorsque les informations sont invalides dans le header.
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                example:
                  erreur: "Requête invalide"
    post:
      tags: 
        - Fakemon
      summary: Ajouter un fakemon.
      description: Il y a besoin d'une clé api dans le header pour pouvoir ajouter un fakemon.
      security:
      - ApiKeyAuth: [] 
      requestBody:
        description: Les informations du fakemon à ajouter.
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  nom:
                    type: string
                  id_type1:
                    type: integer
                  id_type2:
                    type: integer
                  hp:
                    type: integer
                  atk:
                    type: integer
                  def:
                    type: integer
                  sp_atk:
                    type: integer
                  sp_def:
                    type: integer
                  speed: 
                    type: integer
                  description:
                    type: string
            example:
              nom: "Megaroo"
              id_type1: 12
              id_type2: 1
              hp: 120
              atk: 50
              def: 300
              sp_atk: 250
              sp_def: 75
              speed: 60
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."


      responses:
        '201': 
          description: Les informations du fakemon ajouté.
          content:
            application/json:
               schema:
                type: object
                properties:
                  id:
                    type: integer
                  nom:
                    type: string
                  id_type1:
                    type: integer
                  id_type2:
                    type: integer
                  hp:
                    type: integer
                  atk:
                    type: integer
                  def:
                    type: integer
                  sp_atk:
                    type: integer
                  sp_def:
                    type: integer
                  speed: 
                    type: integer
                  description:
                    type: string
                  id_usager:
                    type: integer
                example:
                  id: 253
                  nom: "Megaroo"
                  id_type1: 12
                  id_type2: 1
                  hp: 120
                  atk: 50
                  def: 300
                  sp_atk: 250
                  sp_def: 75
                  speed: 60
                  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat."
                  id_usager: 125
        '401': 
          description: Lorsque les informations sont invalides dans le header.
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                example:
                  erreur: "Requête invalide"
               
  /type:
    get:
      tags:
        - Fakemon
      summary: Récuppérer la liste des types accessibles.
      description: Il y a besoin d'une clé api dans le header pour pouvoir avoir accès à la liste.
      security:
      - ApiKeyAuth: [] 
      responses:
        '200': 
          description: Renvoi la liste des types
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nom:
                          type: string
                example:
                    data : [
                      {
                        id: 1,
                        nom: "Ancun"
                      },
                      {
                        id: 2,
                        nom: "Normal"
                      },
                      {
                        ...: ...
                      }
                    ]
        '401': 
            description: Lorsque les informations sont invalides dans le header.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    api_key:
                      type: string
                  example:
                    erreur: "Requête invalide"
   

components:
  securitySchemes:
    ApiKeyAuth:        
      type: http
      scheme: bearer
      description: "La clé api doit être encoder en base64('27189210-4736-498f-9c54-e15f6a1fdfd6') Exemple de valeur: apikey MjcxODkyMTAtNDczNi00OThmLTljNTQtZTE1ZjZhMWZkZmQ2"
    AccountAuth:
      type: http
      scheme: bearer
      description: "Les infos doivent être encoder en base64('username password') Exemple de valeur: account dXNlciAxMjM0"

      
